### ISSUE TITLE
Import et mise en retrait des citations

### ISSUE THREAD

**Issue by quentinglorieux** [LAbigael/Villey#15]
Lors de l'import d'un word, les citations qui sont mise en retrait (tab) ne sont pas reconnues et donc miise en texte normal.
Elles sont ensuite difficiles à identifier dans l import.

**Comment by quentinglorieux** [comment]
[DP15-T10-Vidal-def.docx](https://github.com/LAbigael/Villey/files/15165992/DP15-T10-Vidal-def.docx)

**Comment by quentinglorieux** [comment]
exemple of texte

**Comment by LAbigael** [comment]
@quentinglorieux J'ai ajouté leur style custom de citation dans la conversion mais ce serait bien qu'ils abandonnent les balises customs dans Word et utiliser celles de base pour une meilleur compatibilité avec notre outil.

**Comment by LAbigael** [comment]
5bcad1b
