### ISSUE TITLE
chapter are shown on the toc but not on the main page

### ISSUE THREAD

**Issue by quentinglorieux** [LAbigael/Villey#22]
chapters are not shown here : https://droitphilosophie.vercel.app/volumes/n15-:-philosophie-de-l'administration.-autour-de-pierre-legendre-131
but here yes : https://droitphilosophie.vercel.app/articles/la-doctrine-du-droit-naturel-face-au-tribunal-de-la-science.-traduction-inedite-de-maude-vidal-de-l'article-de-hans-kelsen-:-the-natural-law-doctrine-before-the-tribunal-of-science-1899

**Comment by quentinglorieux** [comment]
they are also here https://droitphilosophie.vercel.app/volumes

**Comment by LAbigael** [comment]
8e56a51
