### ISSUE TITLE
long footnote

### ISSUE THREAD

**Issue by quentinglorieux** [LAbigael/Villey#23]
si la footnote est trop longue on ne peut pas la lire en entier car pas de barre de défilement

**Comment by quentinglorieux** [comment]
exemple : [8] de https://droitphilosophie.vercel.app/articles/la-doctrine-du-droit-naturel-face-au-tribunal-de-la-science.-traduction-inedite-de-maude-vidal-de-l'article-de-hans-kelsen-:-the-natural-law-doctrine-before-the-tribunal-of-science-1899

**Comment by LAbigael** [comment]
debe512
