### ISSUE TITLE
niveaux de plus sur DP

### ISSUE THREAD

**Issue by quentinglorieux** [LAbigael/Villey#27]
Pouvez-vous ajouter des 3e et 4e niveau de titre pour les articles ?
(I. ... / A. ... / 1. ... / a. ...)

**Comment by LAbigael** [comment]
Ok, j'ai voulu continuer dans la logique les anciens sites. Actuellement on a h3 h4 On aura donc h3, h4, h5 et h6. Ca veut dire que dans le word ce sont ces niveuax qu'il faut utiliser. Est-ce que c'est bon ou on organise une migration de tous les headings dans la base vers h1 h2 h3 h4 ?
