### ISSUE TITLE
pb avec les pdf de DP

### ISSUE THREAD

**Issue by quentinglorieux** [LAbigael/Villey#28]
J'ai constaté, lorsque j'avais accès au site miroir, que les PDF des
articles se téléchargeaient bien, cependant, dès qu'il s'agit
d'hyperlien pour les PDF cela ne fonctionne plus. En effet, nous
n'avons la possibilité que d'ajouter des liens URL aux hyperliens mais
pas de PDF, serait-il possible de corriger cela afin que nous
puissions glisser des PDF dans les dits liens ?

**Comment by LAbigael** [comment]
Non, on ne peux pas ajouter un pdf dans tiptap, il faut connaitre le lien du pdf. En allant sur le front et en copiant le lien du pdf. Sinon ils changent leur manière de faire et mettent un texte pour les ebook  du style "Le pdf est téléchargeable cicontre dans la barre de droite"
