### ISSUE TITLE
[DP] [Priorité basse] Affichage alphabétique des auteurs selon leur patronyme

### ISSUE THREAD

**Issue by ElodieDjordjevic** [LAbigael/Villey#60]
L'affichage standardisé des auteurs sur les deux sites est parfait !

En revanche, serait-il possible de faire en sorte que lorsqu'on arrive sur la page "auteurs" (https://www.droitphilosophie.com/auteurs pour Droit & Philosophie), ce soit d'emblée selon l'ordre alphabétique des patronymes que les auteurs apparaissent (et non selon l'ordre alphabétique des prénoms comme c'est le cas actuellement) ?

@LAbigael

**Comment by ElodieDjordjevic** [comment]
En outre, pour certains auteurs, quand on clique sur leur nom, on est renvoyé vers une page d'erreur. 
Par exemple, si on clique sur "Thibault Desmoulins" sur la page "https://www.droitphilosophie.com/auteurs", on arrive (logiquement) sur la page "https://www.droitphilosophie.com/auteurs/thibault-desmoulins", mais celle-ci affiche cela : 
<img width="735" alt="Capture d’écran 2024-12-08 à 10 59 32" src="https://github.com/user-attachments/assets/f6aa8b5f-ef94-48eb-b9bf-2fb68c3ec1b5">
@LAbigael

**Comment by LAbigael** [comment]
Je viens de regler le "internal servor error" mais j'ai l'impression que le tri est ok à présent.

**Comment by ElodieDjordjevic** [comment]
Le problème "Internal server error" est effectivement dissout, merci !

En revanche, le problème de tri demeure. En réalité, il est seulement présent quand on arrive sur la sorte d’accueil de la page "auteurs", quand on clique simplement sur l'onglet du bandeau par exemple : ça donne ça 👇
<img width="1166" alt="Capture d’écran 2024-12-08 à 11 22 03" src="https://github.com/user-attachments/assets/8cae3141-7b17-4678-bd93-aa73ad816aa8">
(=> tri sur le prénom et non sur le nom)

**Comment by ElodieDjordjevic** [comment]
@LAbigael C'est réglé, mille mercis !!
