### ISSUE TITLE
[DP] [URGENT/Priorité haute] Appel à contributions

### ISSUE THREAD

**Issue by ElodieDjordjevic** [LAbigael/Villey#61]
Je repère bien l'interface créée pour éditer les appels à contributions dans le backoffice, mais 
- Je ne trouve pas le champ "En cours" dont vous parlez dans votre mail du 30/10 qu'il serait possible de modifier pour que l'appel s'affiche sur la page d'accueil ;
- Pour toutes les occurrences (et notamment pour le titre de la page, impossible à éditer pour moi : elle est comme désactivée), il faudrait remplacer "contribution" par "contributions" (ajouter un "s"). Cela vaut également pour le bas de page de la page d'accueil du site et pour la mention "Aucun appel à contributionS en cours". 
- Je voudrais pouvoir maintenir la présence des liens vers les PDF des anciens AAC sur la page "Appel à contributions" (quand elle sera activée.

Un AAC devrait être diffusé d'ici la fin du mois au plus tard en vue de la préparation d'un prochain numéro, les présentes requêtes sont donc plutôt urgentes.

@LAbigael @quentinglorieux

**Comment by LAbigael** [comment]
![image](https://github.com/user-attachments/assets/c885eec2-7d22-4d1b-bc40-15e030cc82f1)

Le champ en cours est disponible en bas de la page des appels à contributions dans le backoffice, comme le montre la capture d'écran. 
Lors de notre appel avec Denis, nous avons convenus qu'il n'était plus nécessaire d'avoir une page 'Appels à contributions', mais que seul celui en cours serait consultable.

**Comment by ElodieDjordjevic** [comment]
Merci de ces précisions ! 
Malheureusement, depuis l'entrée/le compte que j'utilise pour l'édition ("Editeur Villey"), l'interface est différente de la vôtre et je n'ai pas, comme sur votre capture d'écran, la ligne "Appel à contribution" qui est présente pour vous dans la colonne de gauche...
Voici ce que j'ai dans ma version du backoffice : 
<img width="1106" alt="Capture d’écran 2024-11-16 à 11 19 39" src="https://github.com/user-attachments/assets/8456a0a8-3167-4bff-9a62-c4adf96933cb">

**Comment by LAbigael** [comment]
@ElodieDjordjevic Ca devrait être bon ?

**Comment by ElodieDjordjevic** [comment]
@LAbigael Oui, et je viens de tester l'usage de la case "En cours" et ça marche impeccablement, merci !!
En revanche, serait-il possible de prévoir l'ajout de PDF ?

**Comment by LAbigael** [comment]
Ce serait plus simple pour moi de lister les anciens appels à contributions comme avant. Donc des liens vers des pages html. Est-ce que cela peut convenir ?

**Comment by ElodieDjordjevic** [comment]
Oui, ça me semble bien, même si, en réalité, mon souci portait moins sur les anciens appels (comme vous le rappeliez à juste titre, l'idée retenue est bien que le dernier soit accessible), mais la possibilité de pouvoir ajouter un fichier PDF avec l'argument et le calendrier du dernier AAC (que les gens intéressés puissent télécharger : c'est souvent plus pratique). 
Mais si cela est trop compliqué, ce n'est pas très grave (on diffuse aussi l'AAC par mail, avec le PDF en pièce jointe, donc ça devrait aller !) 
@LAbigael

**Comment by LAbigael** [comment]
Je crois que je ne comprends pas. Il faudrait pouvoir ajouter un pdf téléchargeable à la page de l'appel à contribution ?

**Comment by ElodieDjordjevic** [comment]
Oui, c'est exactement cela* ! Mais si ce n'est pas possible, ce n'est pas non plus un drame.
(*) Sur la page de l'appel en cours (par exemple, j'ai pour l'instant activé l'appel "Marx" comme étant "En cours" pour tester et l'idée serait qu'il y ait un PDF téléchargeable sur la page "https://www.droitphilosophie.com/appels-contributions/marx-et-le-droit-appel-ouvert-jusqu'au-15-janvier-2018-1"

**Comment by LAbigael** [comment]
C'est fait ! Je ferme

**Comment by ElodieDjordjevic** [comment]
Je viens de voir : c'est parfait, merci !
