### ISSUE TITLE
[DP] [Priorité moyenne] Les "Hors-Série"

### ISSUE THREAD

**Issue by ElodieDjordjevic** [LAbigael/Villey#62]
J'ai bien vu (et ai bien pu activer le cas échéant) la case "hors-série" dans l'interface d'édition des articles. 
Toutefois, il me semble (mais peut-être les choses ont-elles été modifiées depuis ces observations, que lorsque je me contente de déclarer un article "Hors-série", il ne s'affiche pas nécessairement sur la page "https://www.droitphilosophie.com/hors-series". Pour que ce soit le cas, il faut qu'il soit inséré dans le volume "Hors-série" (création de volume qui est le "bidouillage" adopté sur le précédent site pour pouvoir publier des articles au fil de l'eau, hors numéros constitués). 
Ce n'est pas nécessairement un problème s'il faut s'en tenir à cette solution, mais, quoi qu'il en soit **pouvez-vous nous indiquer si, pour faire les choses "proprement", il faut continuer à insérer ainsi les articles hors-série dans ce volume artificiel ou s'il faut s'y prendre autrement**.

Par ailleurs, pour l'affichage automatique sur la page "https://www.droitphilosophie.com/hors-series", il faut bien maintenir (comme c'est le cas), la partition en rubriques "Numéros" et "Articles", mais l'automatisation des informations affichées n'est pas pleinement satisfaisante en l'état. Il faudrait : 
1) Pour les articles, s'en tenir, je pense à un affichage "simple", qui reprendre tout simplement ce qui s'affiche pour les articles au sein d'un numéro, avec simplement l'ajout, entre crochets, de la date de publication => "Jean Dupont : _Article sur blablabla_ [date de publication]" (avec lien hypertexte vers la page de l'article sur le titre de l'article + titre de l'article en gras et italique)
ex : 
<img width="772" alt="Capture d’écran 2024-11-11 à 09 53 42" src="https://github.com/user-attachments/assets/00203bd2-6b62-40a9-8a08-4e4960a615ad">

Et en tout cas, supprimer absolument les virgules précédées d'espace + les guillemets français collés au texte du titre de l'article + l'espace avant la parenthèse fermante comme c'est le cas actuellement => 
<img width="1016" alt="Capture d’écran 2024-11-11 à 09 58 48" src="https://github.com/user-attachments/assets/8c8f610b-b1b4-4540-b36f-45367a6f16bf">

2) Pour les numéros, là aussi, je serais partisane d'un affichage plus simple des informations (d'autant que certaines ne semblent pas passer, à l'instar des coordinateurs de volume) => Afficher simplement, par exemple, : "**Hors-Série 1 : Normativité et légitimité** [_publié le 15 septembre 2021_]" avec cette mise en forme pour les gras et italique. 
A cet égard, je remarque également que les dates de publications pour l'instant indiquées sont fausses et ne correspondent pas à la date entrée dans l'édition du volume du backoffice ("https://villey.rubidiumweb.eu/admin/content/Volumes/98?bookmark=57" pour le numéro pris pour exemple). Il faudrait que ce soit la date indiquée dans la case "Publié le" qui soit affichée en ligne. 
N.B. :  La rubrique "Numéros" doit accueillir tous les volumes déclarés "Hors-Série" (= les volumes numérotés "-" suivi d'un chiffre arabe).

3) Toutes les occurrences de "Hors-série" (y compris celle du bandeau/onglet") doivent être modifiées en "Hors-Série" ("s" majuscule).

4) Serait-il possible de faire en sorte (en forçant la date par exemple, mais je n'y parviens pas) que la ligne "Hors-Série" apparaisse tout en bas de la liste des anciens numéros telle qu'elle apparaît ici : "https://www.droitphilosophie.com/volumes" et sur la colonne de gauche quand on consulte un ancien numéro (par exemple dans la colonne de droit de : https://www.droitphilosophie.com/volumes/n14-conflit-des-facultes-101) ?

@LAbigael @quentinglorieux

**Comment by LAbigael** [comment]
Les points ont été traités, si l'affichage ne convient pas, vous pouvez toujours re-ouvrir l'issue. Il faudra toujours numéroter les hors-séries avec des chiffres négatifs pour qu'ils apparaissent en bas de la liste des volumes

**Comment by ElodieDjordjevic** [comment]
C'est parfait ainsi pour l'affichage. Bien noté, par ailleurs, pour la numérotation !
