### ISSUE TITLE
[DP] [Priorité moyenne] Les recensions

### ISSUE THREAD

**Issue by ElodieDjordjevic** [LAbigael/Villey#63]
Là aussi, l'ajout et la possible activation de la case "recension" dans l'interface d'édition d'un article a bien été vue et est très pratique !
Pour cette page, contrairement à ce qu'il en est des articles "Hors-Série" (voir Issue #62), tout est parfait et me semble très bien convenir concernant l'affichage.

Toutefois : 
1) là encore, pour la plupart des textes, il m'a semblé que la mise en ligne des pages concernées ne fonctionnait pas si les articles n'étaient pas intégrées à un volume (la page est bien créée avec une adresse etc., mais elle n'est pas mise en ligne). 
Pour contourner ce problème, j'ai procédé au "bidouillage" déjà éprouvé, en créant un bouquet "Recensions" dans le fameux faux volume "Hors-Série", dans lequel j'ai intégré toutes les recensions existantes (exceptées deux qui appartenaient déjà à un volume, en l'occurrence le volume 8. 
Cela fonctionne de cette manière. Faut-il maintenir cette pratique ?

2) Pour une raison que j'ignore, il manque un article, qui refuse absolument de s'afficher dans la liste. Il s'agit de l'article dont l'ID est 1798 (https://villey.rubidiumweb.eu/admin/content/Articles/1798).

3) Comme pour l'ensemble des articles (même si le problème reste ici plus marginal que pour d'autres volumes), les articles se classent en fonction de leur ID et non, comme ce devrait être, en fonction de la position qu'on leur assigne dans le bouquet.

@LAbigael @quentinglorieux

**Comment by LAbigael** [comment]
1. Ce n'est plus nécessaire d'associer une  recension au bouquet recension. L'article peut vivre en dehors d'un volume.
2. L'article 1789 n'avait pas la case "Activé" de cochée.
3. La posistion est bien utilisée pour le tri des recensions mais plusieurs recensions ont la même position dû à leur appartenance à des bouquets différents. La position étant le champ utilisé pour classer les articles au sein d'un bouquet.

**Comment by ElodieDjordjevic** [comment]
@LAbigael : Merci et merci de ces indications !
Je revois ces affaires de positions d'articles dès que possible (et je sors donc les recensions du "faux" volume 0, ce qui simplifiera sans doute les choses)

**Comment by LAbigael** [comment]
@ElodieDjordjevic Est-ce que le sujet est clos ?

**Comment by ElodieDjordjevic** [comment]
Oui, pardon, j'ai effectivement oublié de le faire !
